##############################################################################
# Template generated by SiliconSmart L-2016.06-SP1-2 (built on Dec 07, 2016 16:59:49) #
# SiliconSmart Path: /acsnfs3/software/SiliconSmartAce-2016.06-SP1-2/linux64/bin/siliconsmart #
# Host Name: ieng6-249.ucsd.edu, User Name: haz023, PID: 5326 #
# Directory: /home/linux/ieng6/ee260bwi20/haz023/lab5/run_siliconsmart/LIB_FF_1.1_-40_ALL #
# Date Fri, 21 Feb 2020 15:13:54 PST #
#                                                                            #
# Copyright (C) 2016 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower }

## 
## Formal Ports
$tempTestColl makeFormalPorts {Q SDN CDN CP D}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {SDN CDN}
$tempTestColl setParameter clock_ports {CP}
$tempTestColl setParameter asynch_ports {SDN CDN}
$tempTestColl setParameter asynch_ports_active_state {CDN 10 SDN 10}

## 
## Tests

## 
## Test cmpw__CDN__hl__CDN__lh
set tempTest [ SBTest "cmpw__CDN__hl__CDN__lh" ]
$tempTest setTargets { cmpw__CDN__hl__CDN__lh }
$tempTest setTargetInputs {
  {CDN hl}}

$tempTest setTargetOutputs {
  {Q hl}}

$tempTest setTargetReferences {
  {CDN lh}}

$tempTest setSwitchingInputs {
  {CDN hl}}

$tempTest setSwitchingRefs {
  {CDN lh}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1
$tempTest setStateCoverage "SDN"

## 
## ACQ_1
set tempAcq [ SBMPWAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "SDN&!CP&!D"
$tempAcq setStateCoverage "SDN"
$tempAcq setWhen "1"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { Q:out SDN CP CDN D } { initial_delay units ct default_slew stable cmpw min_cmpw max_cmpw opt_tolerance }

$tempWT setStimulus                                              {   SDN  CP   CDN  D    Q     } {
                                                 "0"          {} {   0    0    0    0    1     }
                                     "initial_delay"          {} {   -    -    1    -    -     }
                           "initial_delay+0.5*units"          {} {   1    -    -    -    -     }
                             "initial_delay+1*units" { in1 out } {   -    -    0    -    0     }
           "(initial_delay+1*units)+cmpw+slew_CDN*3"     { in2 } {   -    -    1    -    -     }
"((initial_delay+1*units)+cmpw+slew_CDN*3)+(stable)"          {} {   -    -    -    -    -     }
}

$tempWT addMeasurements {} {
  { tin_CDN              Tin        { CDN in1 } NO_USER SYS }
  { cmpw_CDN             cmpw       { CDN in1 CDN in2 } NO_USER SYS }
  { tout_Q               Tout       { Q in1 } NO_USER SYS }
  { delay_CDN_Q          delay      { CDN in1 Q in1 } NO_USER SYS }
  { fallback_Q           fallback   { Q in1 0 } NO_USER SYS }
}

$tempWT addOptimization    cmpw    min_cmpw    max_cmpw    delay_CDN_Q    { cmpw_CDN tin_CDN tin_CDN tout_Q delay_CDN_Q } { fallback_Q } {  } {  } expand None opt_tolerance None None max_cmpw "1"
$tempWT bindInterface { Q SDN CP CDN D } { cell_initial_delay CDN[cycle_time] CDN[cycle_time] CDN[default_slew] max(CDN[stable_time],Q[stable_time]) CDN[max_cmpw] CDN[min_cmpw] CDN[max_cmpw] CDN[constraint_resolution] }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_Q
$tempTopOp setOperation insert
$tempTopOp setNodes {Q Q[logic_low_name]}
$tempTopOp setParam {load_Q}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

