##############################################################################
# Template generated by SiliconSmart L-2016.06-SP1-2 (built on Dec 07, 2016 16:59:49) #
# SiliconSmart Path: /acsnfs3/software/SiliconSmartAce-2016.06-SP1-2/linux64/bin/siliconsmart #
# Host Name: ieng6-249.ucsd.edu, User Name: haz023, PID: 5262 #
# Directory: /home/linux/ieng6/ee260bwi20/haz023/lab5/run_siliconsmart/LIB_FF_1.1_-40_ALL #
# Date Fri, 21 Feb 2020 15:13:52 PST #
#                                                                            #
# Copyright (C) 2016 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower }

## 
## Formal Ports
$tempTestColl makeFormalPorts {Q E D}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {E}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test Cin__E__hl
set tempTest [ SBTest "Cin__E__hl" ]
$tempTest setTargets { Cin__E__hl }
$tempTest setTargetInputs {
  {E hl}}

$tempTest setSwitchingInputs {
  {E hl}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification

## 
## Harnesses
$tempTest setAcquire 1

## 
## ACQ_2
set tempAcq [ SBInputCapacitanceAcquisition "ACQ_2" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "D"
$tempAcq setStateCoverage "D"
$tempAcq setWhen "1"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { Q:out E D } { initial_delay units ct default_slew pp }

$tempWT setStimulus                      {   E    D    Q     } {
                             "0"      {} {   1    0    0     }
                 "initial_delay"      {} {   0    -    -     }
       "initial_delay+0.5*units"      {} {   -    1    -     }
         "initial_delay+1*units"      {} {   1    -    1     }
       "initial_delay+1.5*units" { in1 } {   0    -    1     }
"(initial_delay+1.5*units)+(pp)"      {} {   -    -    -     }
}

$tempWT addMeasurements {} {
  { cin_E                Cin        { E in1 } NO_USER SYS }
}

$tempWT bindInterface { Q E D } { cell_initial_delay E[cycle_time] E[cycle_time] E[default_slew] cell_power_period }
$tempAcq addWaveTable $tempWT
release_obj $tempWT
$tempAcq setRelatedAcq "delay__E__lh__Q__lh__ACQ_1"

## 
## Sweep Specification

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_Q
$tempTopOp setOperation insert
$tempTopOp setNodes {Q Q[logic_low_name]}
$tempTopOp setParam {load_Q}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

