##############################################################################
# Template generated by SiliconSmart L-2016.06-SP1-2 (built on Dec 07, 2016 16:59:49) #
# SiliconSmart Path: /acsnfs3/software/SiliconSmartAce-2016.06-SP1-2/linux64/bin/siliconsmart #
# Host Name: ieng6-249.ucsd.edu, User Name: haz023, PID: 5262 #
# Directory: /home/linux/ieng6/ee260bwi20/haz023/lab5/run_siliconsmart/LIB_FF_1.1_-40_ALL #
# Date Fri, 21 Feb 2020 15:13:51 PST #
#                                                                            #
# Copyright (C) 2016 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower }

## 
## Formal Ports
$tempTestColl makeFormalPorts {Q E D}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {E}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test cmpw__E__lh__E__hl
set tempTest [ SBTest "cmpw__E__lh__E__hl" ]
$tempTest setTargets { cmpw__E__lh__E__hl }
$tempTest setTargetInputs {
  {E lh}}

$tempTest setTargetOutputs {
  {Q lh}}

$tempTest setTargetReferences {
  {E hl}}

$tempTest setSwitchingInputs {
  {E lh}}

$tempTest setSwitchingRefs {
  {E hl}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1

## 
## ACQ_1
set tempAcq [ SBMPWAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "D"
$tempAcq setStateCoverage "1"
$tempAcq setWhen "1"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { Q:out E D } { initial_delay units ct default_slew stable cmpw min_cmpw max_cmpw opt_tolerance }

$tempWT setStimulus                                            {   E    D    Q     } {
                                               "0"          {} {   1    0    0     }
                                   "initial_delay"          {} {   0    -    -     }
                         "initial_delay+0.5*units"          {} {   -    1    -     }
                           "initial_delay+1*units" { in1 out } {   1    -    1     }
           "(initial_delay+1*units)+cmpw+slew_E*3"     { in2 } {   0    -    -     }
"((initial_delay+1*units)+cmpw+slew_E*3)+(stable)"          {} {   -    -    -     }
}

$tempWT addMeasurements {} {
  { tin_E                Tin        { E in1 } NO_USER SYS }
  { cmpw_E               cmpw       { E in1 E in2 } NO_USER SYS }
  { tout_Q               Tout       { Q in1 } NO_USER SYS }
  { delay_E_Q            delay      { E in1 Q in1 } NO_USER SYS }
  { fallback_Q           fallback   { Q in1 0 } NO_USER SYS }
}

$tempWT addOptimization    cmpw    min_cmpw    max_cmpw    delay_E_Q    { cmpw_E tin_E tin_E tout_Q delay_E_Q } { fallback_Q } {  } {  } expand None opt_tolerance None None max_cmpw "1"
$tempWT bindInterface { Q E D } { cell_initial_delay E[cycle_time] E[cycle_time] E[default_slew] max(E[stable_time],Q[stable_time]) E[max_cmpw] E[min_cmpw] E[max_cmpw] E[constraint_resolution] }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_Q
$tempTopOp setOperation insert
$tempTopOp setNodes {Q Q[logic_low_name]}
$tempTopOp setParam {load_Q}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

