* StarRCXT command file for 65nm worst corner

LEF_FILE: %%%%PATH_AND_FILE_NAME%%%%

LEF_USE_OBS: NO

TOP_DEF_FILE: %%%%PATH_AND_FILE_NAME%%%%

TCAD_GRD_FILE: %%%%PATH_AND_FILE_NAME_FOR_CAP_WORST%%%%

MAPPING_FILE: %%%%PATH_AND_FILE_NAME%%%%

EXTRACTION: RC

TARGET_ANALYSIS: NONE

MODE: 100

REDUCTION: YES

NETLIST_FORMAT: SPEF

NETLIST_FILE: aes_cipher_top.spef

OPERATING_TEMPERATURE: 125

